// ── 콘텐츠 데이터 ──
// 지역명만 바꾼 중복 문장을 피하기 위해 각 지역·생활권마다 고유한 특징/교통/숙소 기준을 작성합니다.

// 12대 광역 생활권 (메인 카드 & /area/*)
const areas = [
  {
    slug: 'cheonan-buldang-dujeong',
    name: '천안 불당·두정권',
    h1: '천안 불당·두정 출장마사지 · 생활권 방문 안내',
    title: '천안 불당·두정 출장마사지｜쌍용·성정·천안아산역 안내',
    desc: '천안 불당·쌍용·두정·성정·신부·천안아산역 생활권 숙소 이용 전 확인사항 안내.',
    includes: ['불당', '쌍용', '두정', '성정', '신부', '천안터미널', '천안아산역'],
    region: 'cheonan',
    life: '천안은 충청 북부에서 검색 수요가 강한 교통·신도시 도시입니다. 불당·쌍용은 오피스텔과 신축 아파트가 밀집한 신도시 생활권이고, 두정·성정은 상권과 비즈니스 숙소가 이어지는 축입니다. 신부동과 천안종합터미널은 시외·고속 교통의 중심이며, 천안아산역은 KTX·SRT 환승 수요가 몰리는 거점입니다.',
    transport: '천안아산역(KTX·SRT), 천안역, 두정역, 천안종합터미널이 핵심 거점입니다. 불당·쌍용에서는 천안아산역까지 차량 이동이 짧고, 신부동에서는 터미널 접근성이 좋습니다.',
    programs: ['swedish', 'aroma-therapy', 'thai-massage'],
    related: ['daejeon-dunsan-yuseong', 'gwangju-sangmu-suwan'],
  },
  {
    slug: 'daejeon-dunsan-yuseong',
    name: '대전 둔산·유성권',
    h1: '대전 둔산·유성 출장마사지 · 업무·숙소 생활권 안내',
    title: '대전 둔산·유성 출장마사지｜탄방·봉명·도안 생활권 안내',
    desc: '대전 둔산·탄방·유성·봉명·도안 업무·호텔·대학가 생활권 이용 기준 안내.',
    includes: ['둔산', '탄방', '월평', '유성', '봉명', '궁동', '노은', '반석', '도안'],
    region: 'daejeon',
    life: '대전의 핵심 업무·숙소·대학가 생활권입니다. 서구 둔산·탄방은 관공서와 오피스가 밀집한 업무지구이고, 유성·봉명은 호텔·숙소와 대학가가 이어지는 관광·비즈니스 축입니다. 도안·관저는 신도시 아파트 단지 중심으로, 생활권마다 건물 출입 방식과 이용 기준이 다릅니다.',
    transport: '유성온천역, 시청역, 정부청사역이 지하철 거점이며 유성고속버스터미널이 인접합니다. 둔산 정부청사 일대는 오피스 밀집, 유성은 호텔 밀집 구역입니다.',
    programs: ['sports-massage', 'foot-massage', 'aroma-therapy'],
    related: ['daejeon-station-daedeok', 'cheonan-buldang-dujeong'],
  },
  {
    slug: 'daejeon-station-daedeok',
    name: '대전역·원도심·대덕권',
    h1: '대전역·원도심·대덕 출장마사지 · 교통·주거 생활권 안내',
    title: '대전역·원도심·대덕 출장마사지｜은행·대흥·신탄진 안내',
    desc: '대전역·중앙로·은행·대흥·대덕구 신탄진 원도심 및 주거권 이용 기준 안내.',
    includes: ['대전역', '중앙로', '은행', '대흥', '용전', '송촌', '중리', '신탄진'],
    region: 'daejeon',
    life: '대전역과 원도심, 대덕구 주거권을 아우르는 생활권입니다. 대전역·용전은 KTX·터미널이 몰린 교통 중심이고, 은행·대흥은 오래된 상권과 도심 숙소가 남아 있는 원도심입니다. 대덕구 송촌·중리·신탄진은 주거지와 산업권이 섞여 북대전 이동 기준이 함께 필요합니다.',
    transport: 'KTX 대전역과 동부·유성 시외버스, 신탄진역이 축이 됩니다. 대덕연구단지·산업권 이동 시에는 신탄진·용전 방향 동선을 함께 확인합니다.',
    programs: ['foot-massage', 'deep-tissue', 'sports-massage'],
    related: ['daejeon-dunsan-yuseong', 'iksan-gunsan-saemangeum'],
  },
  {
    slug: 'gwangju-sangmu-suwan',
    name: '광주 상무·수완권',
    h1: '광주 상무·수완 출장마사지 · 도심 생활권 안내',
    title: '광주 상무·수완 출장마사지｜첨단·금남로·송정 생활권 안내',
    desc: '광주 상무지구·수완·첨단·금남로·송정역 도심 생활권 이용 기준 안내.',
    includes: ['상무지구', '수완지구', '첨단', '금남로', '충장로', '광천', '송정'],
    region: 'honam',
    life: '광주 도심의 업무·상권·신도시가 이어지는 생활권입니다. 상무지구는 오피스와 호텔이 밀집한 업무 중심, 수완·첨단은 신도시 아파트와 상권이 형성된 주거권입니다. 금남로·충장로는 원도심 상권, 광천·송정은 터미널·KTX 광주송정역이 있는 교통 축입니다. 행정명 변경 이슈가 있어도 실제 검색 수요는 상무·수완·첨단 중심으로 유지됩니다.',
    transport: 'KTX 광주송정역과 광주종합버스터미널(유스퀘어)이 핵심입니다. 상무·수완에서 송정역까지 차량 이동이 짧아 출장 숙소 접근성이 좋습니다.',
    programs: ['aroma-therapy', 'swedish', 'foot-massage'],
    related: ['jeonju-wanju-innovation', 'yeosu-suncheon-gwangyang'],
  },
  {
    slug: 'jeonju-wanju-innovation',
    name: '전주·완주 혁신도시권',
    h1: '전주·완주 출장마사지 · 혁신도시·도심 생활권 안내',
    title: '전주·완주 출장마사지｜완산·덕진·혁신도시 생활권 안내',
    desc: '전주 완산·덕진·전주혁신도시·완주 삼례·봉동 생활권 이용 기준 안내.',
    includes: ['전주 완산', '덕진', '전주혁신도시', '완주 이서', '삼례', '봉동'],
    region: 'honam',
    life: '전북의 핵심 도시권입니다. 전주 완산·덕진은 도심 숙소와 오피스텔, 한옥마을 인접 관광 숙소가 이어지는 축이고, 전주혁신도시는 이주 공공기관과 신축 오피스텔이 밀집한 구역입니다. 완주 이서·삼례·봉동은 산업권과 외곽 주거지가 섞여 이동 기준을 함께 확인해야 합니다.',
    transport: 'KTX 전주역과 전주고속버스터미널이 축입니다. 혁신도시에서는 이서·삼례 방향 외곽 이동 기준, 완주 산업권은 차량 동선 확인이 중요합니다.',
    programs: ['thai-massage', 'sports-massage', 'aroma-therapy'],
    related: ['iksan-gunsan-saemangeum', 'gwangju-sangmu-suwan'],
  },
  {
    slug: 'iksan-gunsan-saemangeum',
    name: '익산·군산·새만금권',
    h1: '익산·군산·새만금 출장마사지 · 교통·산업 생활권 안내',
    title: '익산·군산·새만금 출장마사지｜익산역·군산산단 안내',
    desc: '익산역·원광대·군산산단·새만금 장기 체류 숙소 이용 기준 안내.',
    includes: ['익산', '군산', '익산역', '원광대', '군산산단', '새만금'],
    region: 'honam',
    life: 'KTX 익산역을 중심으로 한 교통 거점과 군산·새만금 산업권이 함께 묶인 생활권입니다. 익산은 역세권 숙소와 원광대 대학가, 군산은 산업단지와 근대문화거리 인접 숙소, 새만금은 개발권 인접 장기 체류 숙소가 특징입니다. 산업권 출장 수요가 많아 오피스텔·비즈니스 숙소 이용 기준이 중요합니다.',
    transport: 'KTX 익산역과 군산역, 군산고속버스터미널이 축입니다. 새만금·군산산단 방향은 차량 이동 거리가 있어 예약 전 위치 확인이 필요합니다.',
    programs: ['sports-massage', 'deep-tissue', 'foot-massage'],
    related: ['jeonju-wanju-innovation', 'mokpo-naju-muan'],
  },
  {
    slug: 'yeosu-suncheon-gwangyang',
    name: '여수·순천·광양권',
    h1: '여수·순천·광양 출장마사지 · 전남 동부 생활권 안내',
    title: '여수·순천·광양 출장마사지｜신대지구·광양항 생활권 안내',
    desc: '여수 관광 숙소·순천 신대지구·광양항 산단 인접 이용 기준 안내.',
    includes: ['여수', '순천', '광양', '여수산단', '광양항', '순천 신대지구'],
    region: 'honam',
    life: '호남권에서 중요한 전남 동부 생활권입니다. 여수는 관광 숙소와 여수산단이 공존해 해안 호텔 이용 기준이 중요하고, 순천은 도심과 신대지구·역세권 숙소가 이어집니다. 광양은 항만·제철 산단과 출장 숙소 중심으로, 세 도시 모두 관광 성수기와 산업 출장 수요가 겹칩니다.',
    transport: '여수엑스포역, 순천역, 광양읍 시외버스가 축입니다. 여수 관광 숙소, 순천 신대지구, 광양 산단은 각각 이동 동선이 달라 위치 확인이 필요합니다.',
    programs: ['foot-massage', 'aroma-therapy', 'sports-massage'],
    related: ['gwangju-sangmu-suwan', 'mokpo-naju-muan'],
  },
  {
    slug: 'mokpo-naju-muan',
    name: '목포·나주·무안권',
    h1: '목포·나주·무안 출장마사지 · 서남권 생활권 안내',
    title: '목포·나주·무안 출장마사지｜남악·혁신도시 생활권 안내',
    desc: '목포 해안 숙소·나주혁신도시·무안 남악 행정권 이용 기준 안내.',
    includes: ['목포', '남악', '무안', '나주혁신도시', '영암', '해남 인접권'],
    region: 'honam',
    life: '전남 서남권의 행정·관광 생활권입니다. 목포는 해안 숙소와 목포역·터미널 중심의 교통권, 나주는 이전 공공기관이 모인 나주혁신도시 오피스텔권, 무안·남악은 전남도청이 있는 행정 신도시 생활권입니다. 영암·해남 인접권은 외곽 이동 기준을 함께 확인합니다.',
    transport: 'KTX 목포역과 목포종합버스터미널, 남악·오룡 신도시가 축입니다. 나주혁신도시는 별도 동선, 무안공항 인접권은 이동 거리를 확인합니다.',
    programs: ['aroma-therapy', 'foot-massage', 'swedish'],
    related: ['yeosu-suncheon-gwangyang', 'iksan-gunsan-saemangeum'],
  },
  {
    slug: 'chuncheon-hongcheon',
    name: '춘천·홍천권',
    h1: '춘천·홍천 출장마사지 · 강원 내륙 생활권 안내',
    title: '춘천·홍천 출장마사지｜남춘천역·리조트 인접 안내',
    desc: '춘천 도심·역세권과 홍천 리조트·펜션 외곽 이동 기준 안내.',
    includes: ['춘천', '홍천', '춘천역', '남춘천역', '홍천읍', '비발디파크 인접권'],
    region: 'gangwon',
    life: '강원 내륙의 핵심 도시와 리조트권입니다. 춘천은 대학가와 역세권, 주거지, 호수 관광 숙소가 함께 있는 도심형 생활권이고, 홍천은 비발디파크·리조트와 펜션이 흩어진 외곽 이동 중심 생활권입니다. 도심형 춘천과 숙소형 홍천은 접근 방식이 크게 달라 숙소 유형별 기준을 나눠 확인합니다.',
    transport: 'ITX 춘천역·남춘천역이 축이며, 홍천은 철도가 없어 시외버스와 차량 이동 기준이 중요합니다. 리조트권은 프런트·객실 출입 정책을 먼저 확인합니다.',
    programs: ['sports-massage', 'thai-massage', 'aroma-therapy'],
    related: ['wonju-hoengseong', 'gangneung-donghae-samcheok'],
  },
  {
    slug: 'wonju-hoengseong',
    name: '원주·횡성권',
    h1: '원주·횡성 출장마사지 · 혁신·기업도시 생활권 안내',
    title: '원주·횡성 출장마사지｜무실·반곡혁신도시·문막 안내',
    desc: '원주 무실·단계·반곡혁신도시·기업도시·횡성 외곽 이동 기준 안내.',
    includes: ['원주', '무실', '단계', '반곡혁신도시', '기업도시', '문막', '횡성', '둔내'],
    region: 'gangwon',
    life: '강원권에서 업무·혁신도시 성격이 강한 생활권입니다. 원주는 무실·단계 도심 오피스텔, 반곡동 혁신도시, 지정면 기업도시로 이어지는 출장 수요가 큽니다. 문막은 산업권, 횡성·둔내는 리조트·외곽 이동권으로, KTX 원주역과 함께 도심·외곽 기준을 나눠 안내합니다.',
    transport: 'KTX 원주역(만종)과 원주고속버스터미널이 축입니다. 혁신도시·기업도시는 도심에서 떨어져 있어 이동 동선 확인이 필요하고, 횡성·둔내는 외곽 이동 기준을 함께 봅니다.',
    programs: ['sports-massage', 'thai-massage', 'foot-massage'],
    related: ['chuncheon-hongcheon', 'gangneung-donghae-samcheok'],
  },
  {
    slug: 'gangneung-donghae-samcheok',
    name: '강릉·동해·삼척권',
    h1: '강릉·동해·삼척 출장마사지 · 동해안 생활권 안내',
    title: '강릉·동해·삼척 출장마사지｜경포·묵호·관광 숙소 안내',
    desc: '강릉역·경포·안목·동해 묵호·삼척 해안 관광 숙소 이용 기준 안내.',
    includes: ['강릉', '강릉역', '경포', '안목', '주문진', '동해', '묵호', '삼척', '쏠비치 인접권'],
    region: 'gangwon',
    life: '동해안의 핵심 관광·주거 생활권입니다. 강릉은 KTX 강릉역과 경포·안목·교동 상권, 관광 숙소가 몰린 도시이고, 동해는 항만과 묵호·천곡 주거·숙소권입니다. 삼척은 해안 리조트와 관광 숙소 중심으로, 성수기 관광 숙소 이용 기준과 이동 동선이 특히 중요합니다.',
    transport: 'KTX 강릉역과 정동진역, 동해역, 삼척 시외버스가 축입니다. 경포·안목 관광 숙소, 묵호항, 쏠비치 인접권은 각각 이동 거리를 확인합니다.',
    programs: ['aroma-therapy', 'foot-massage', 'swedish'],
    related: ['sokcho-pyeongchang-resort', 'wonju-hoengseong'],
  },
  {
    slug: 'sokcho-pyeongchang-resort',
    name: '속초·평창·강원 관광숙소권',
    h1: '속초·평창 출장마사지 · 관광 숙소·리조트 생활권 안내',
    title: '속초·평창 출장마사지｜양양·정선 리조트·펜션 숙소 안내',
    desc: '속초·양양·고성 해안 숙소와 평창·정선 리조트·펜션 이용 기준 안내.',
    includes: ['속초', '양양', '고성', '평창', '정선', '태백', '리조트·펜션 숙소권'],
    region: 'gangwon',
    life: '강원 북동부 해안과 산악 리조트를 아우르는 관광 숙소 생활권입니다. 속초·양양·고성은 해안 호텔과 서핑·펜션 숙소, 평창·정선은 스키장·리조트와 산악 관광 숙소 중심입니다. 얇은 읍면 단위보다 관광 숙소 유형과 이동 기준이 더 중요해, 리조트·펜션 이용 정책을 우선 안내합니다.',
    transport: '속초고속버스터미널, 양양(서울양양고속도로), KTX 진부(오대산)·평창역이 축입니다. 리조트·펜션은 프런트 확인과 객실 출입 정책, 겨울철 도로 상황을 먼저 확인합니다.',
    programs: ['aroma-therapy', 'foot-massage', 'couple'],
    related: ['gangneung-donghae-samcheok', 'chuncheon-hongcheon'],
  },
];

// 4대 권역
const regions = [
  {
    slug: 'cheonan',
    name: '천안권',
    h1: '천안 출장마사지 · 불당·두정·천안아산역 생활권 안내',
    title: '천안 출장마사지｜불당·두정·천안아산역 생활권 안내',
    desc: '천안 서북구·동남구 불당·두정·신부·천안아산역 생활권 이용 기준 안내.',
    intro: '천안은 서북구·동남구를 모두 포함하되, 실제 검색 수요는 불당·두정·성정·신부·천안아산역 생활권에 집중됩니다. 오피스텔·아파트·터미널·KTX·SRT 접근성과 출장 숙소 기준을 생활권별로 안내합니다.',
    districts: [
      { slug: 'seobuk-gu', name: '서북구' },
      { slug: 'dongnam-gu', name: '동남구' },
    ],
    areas: ['cheonan-buldang-dujeong'],
    keywords: ['천안 출장마사지', '천안 불당 출장마사지', '천안아산역 출장마사지', '두정 출장마사지'],
  },
  {
    slug: 'daejeon',
    name: '대전권',
    h1: '대전 출장마사지 · 둔산·유성·대전역 생활권 안내',
    title: '대전 출장마사지｜둔산·유성·대전역 생활권 안내',
    desc: '대전 5개 구 둔산·유성·대전역·도안·대덕 생활권 이용 기준 안내.',
    intro: '대전은 5개 구를 모두 포함하되, 둔산·탄방 업무지구와 유성·봉명 숙소권, 대전역·원도심을 먼저 강화합니다. 도안·관저 신도시와 대덕·신탄진 산업·주거권 이동 기준을 함께 안내합니다.',
    districts: [
      { slug: 'seo-gu', name: '서구' },
      { slug: 'yuseong-gu', name: '유성구' },
      { slug: 'dong-gu', name: '동구' },
      { slug: 'jung-gu', name: '중구' },
      { slug: 'daedeok-gu', name: '대덕구' },
    ],
    areas: ['daejeon-dunsan-yuseong', 'daejeon-station-daedeok'],
    keywords: ['대전 출장마사지', '대전 둔산 출장마사지', '대전 유성 출장마사지', '대전역 출장마사지'],
  },
  {
    slug: 'honam',
    name: '호남권',
    h1: '호남 출장마사지 · 광주·전주·여수·순천 생활권 안내',
    title: '호남 출장마사지｜광주·전주·여수·순천·목포 생활권 안내',
    desc: '광주·전주·여수·순천·목포 호남권 도시별 생활권 이용 기준 안내.',
    intro: '호남권은 광주·상무·수완·첨단, 전주·완주, 익산·군산, 여수·순천·광양, 목포·나주·무안으로 나눕니다. 광주·전남은 전남광주통합특별시 행정명과 기존 도시명 검색 수요를 함께 반영합니다.',
    districts: [
      { slug: 'gwangju', name: '광주' },
      { slug: 'jeonju-si', name: '전주시' },
      { slug: 'iksan-si', name: '익산시' },
      { slug: 'gunsan-si', name: '군산시' },
      { slug: 'yeosu-si', name: '여수시' },
      { slug: 'suncheon-si', name: '순천시' },
      { slug: 'gwangyang-si', name: '광양시' },
      { slug: 'mokpo-si', name: '목포시' },
      { slug: 'naju-si', name: '나주시' },
      { slug: 'jeongeup-si', name: '정읍시' },
      { slug: 'namwon-si', name: '남원시' },
      { slug: 'gimje-si', name: '김제시' },
    ],
    areas: ['gwangju-sangmu-suwan', 'jeonju-wanju-innovation', 'iksan-gunsan-saemangeum', 'yeosu-suncheon-gwangyang', 'mokpo-naju-muan'],
    keywords: ['호남 출장마사지', '광주 출장마사지', '전주 출장마사지', '여수 출장마사지', '목포 출장마사지'],
  },
  {
    slug: 'gangwon',
    name: '강원권',
    h1: '강원도 출장마사지 · 춘천·원주·강릉·속초 관광 숙소 안내',
    title: '강원도 출장마사지｜춘천·원주·강릉·속초 관광 숙소 안내',
    desc: '강원특별자치도 춘천·원주·강릉·속초 도시와 리조트·펜션 이용 안내.',
    intro: '강원권(강원특별자치도)은 도심형보다 호텔·펜션·리조트·동해안 숙소·KTX·산간 외곽 이동 기준이 중요합니다. 춘천·원주·강릉·속초를 핵심 도시로 색인하고, 평창·정선·홍천은 리조트·펜션 페이지와 연결합니다.',
    districts: [
      { slug: 'chuncheon-si', name: '춘천시' },
      { slug: 'wonju-si', name: '원주시' },
      { slug: 'gangneung-si', name: '강릉시' },
      { slug: 'sokcho-si', name: '속초시' },
      { slug: 'donghae-si', name: '동해시' },
      { slug: 'samcheok-si', name: '삼척시' },
      { slug: 'hongcheon-gun', name: '홍천군' },
      { slug: 'pyeongchang-gun', name: '평창군' },
      { slug: 'jeongseon-gun', name: '정선군' },
      { slug: 'yangyang-gun', name: '양양군' },
      { slug: 'goseong-gun', name: '고성군' },
    ],
    areas: ['chuncheon-hongcheon', 'wonju-hoengseong', 'gangneung-donghae-samcheok', 'sokcho-pyeongchang-resort'],
    keywords: ['강원도 출장마사지', '춘천 출장마사지', '원주 출장마사지', '강릉 출장마사지', '속초 출장마사지'],
  },
];

// 마사지 프로그램
const programs = [
  { slug: 'swedish', name: '스웨디시', title: '스웨디시 마사지 안내｜부드러운 전신 릴렉스 케어', desc: '부드러운 오일 압으로 전신 순환과 피로를 풀어주는 스웨디시 안내.',
    intro: '스웨디시는 오일을 사용해 부드럽고 일정한 압으로 전신을 쓸어주는 릴렉스 중심 프로그램입니다. 근육을 세게 누르기보다 순환과 이완에 초점을 맞춰, 장시간 이동·업무로 지친 몸을 부담 없이 풀고 싶은 분께 적합합니다.',
    good: '전신 피로 완화, 수면 개선, 첫 방문 릴렉스 케어',
    areas: ['cheonan-buldang-dujeong', 'daejeon-dunsan-yuseong', 'gwangju-sangmu-suwan', 'gangneung-donghae-samcheok'] },
  { slug: 'thai-massage', name: '타이마사지', title: '타이마사지 안내｜스트레칭 중심 전신 이완', desc: '스트레칭과 지압을 결합해 관절·근육을 풀어주는 타이마사지 안내.',
    intro: '타이마사지는 스트레칭과 지압을 결합해 관절 가동 범위와 근육 긴장을 함께 다루는 프로그램입니다. 오일을 쓰지 않고 편한 복장으로 진행하며, 뻐근함이 오래 누적된 분이나 유연성 관리가 필요한 분께 적합합니다.',
    good: '근육 긴장 완화, 스트레칭, 자세 피로 관리',
    areas: ['cheonan-buldang-dujeong', 'jeonju-wanju-innovation', 'wonju-hoengseong', 'chuncheon-hongcheon'] },
  { slug: 'aroma-therapy', name: '아로마테라피', title: '아로마테라피 안내｜향과 오일 중심 심신 이완', desc: '아로마 오일 향과 부드러운 압으로 심신을 이완하는 아로마 케어 안내.',
    intro: '아로마테라피는 목적에 맞는 아로마 오일을 사용해 향과 촉감으로 긴장을 낮추는 프로그램입니다. 부드러운 압과 함께 심리적 이완에 초점을 맞춰, 스트레스·불면·긴장이 누적된 분께 적합합니다.',
    good: '스트레스 완화, 긴장·불면 관리, 심신 이완',
    areas: ['daejeon-dunsan-yuseong', 'jeonju-wanju-innovation', 'yeosu-suncheon-gwangyang', 'sokcho-pyeongchang-resort'] },
  { slug: 'sports-massage', name: '스포츠 마사지', title: '스포츠 마사지 안내｜근육·회복 중심 관리', desc: '운동·업무로 뭉친 근육을 집중 관리하는 스포츠 마사지 안내.',
    intro: '스포츠 마사지는 특정 근육군의 긴장과 피로를 집중적으로 다루는 회복 중심 프로그램입니다. 운동 전후 컨디셔닝이나 반복 업무로 뭉친 부위를 강한 압으로 관리하고 싶은 분께 적합합니다.',
    good: '근육 회복, 뭉침 완화, 운동 전후 관리',
    areas: ['daedeok-research-area', 'gunsan-saemangeum-industrial', 'wonju-hoengseong', 'daejeon-dunsan-yuseong'] },
  { slug: 'foot-massage', name: '발마사지', title: '발마사지 안내｜발·종아리 순환 관리', desc: '오래 걷거나 서 있어 지친 발·종아리 순환을 풀어주는 발마사지 안내.',
    intro: '발마사지는 발바닥 반사구와 종아리를 중심으로 순환과 피로를 풀어주는 프로그램입니다. 오래 걷거나 서서 일한 뒤, 이동이 잦은 출장 중 가볍게 컨디션을 회복하고 싶을 때 적합합니다.',
    good: '발·종아리 피로, 부기 완화, 순환 관리',
    areas: ['daejeon-station-daedeok', 'gwangju-sangmu-suwan', 'jeonju-wanju-innovation', 'gangneung-donghae-samcheok'] },
  { slug: 'deep-tissue', name: '딥티슈', title: '딥티슈 마사지 안내｜심부 근막 집중 케어', desc: '깊은 근막층까지 집중해 만성 뭉침을 다루는 딥티슈 안내.',
    intro: '딥티슈는 표층보다 깊은 근막층을 겨냥해 만성적으로 굳은 부위를 천천히 풀어주는 프로그램입니다. 강한 압을 선호하고 특정 부위의 오래된 뭉침을 집중 관리하고 싶은 분께 적합합니다.',
    good: '만성 뭉침, 심부 근막, 강한 압 선호',
    areas: ['daejeon-station-daedeok', 'iksan-gunsan-saemangeum'] },
  { slug: 'lomi-lomi', name: '로미로미', title: '로미로미 안내｜리드미컬한 하와이안 케어', desc: '팔 전체를 이용한 리드미컬한 흐름의 로미로미 릴렉스 안내.',
    intro: '로미로미는 팔뚝 전체를 이용해 파도처럼 이어지는 리드미컬한 동작으로 전신을 이완하는 하와이안 스타일 프로그램입니다. 끊김 없는 흐름의 릴렉스를 선호하는 분께 적합합니다.',
    good: '전신 릴렉스, 리드미컬 케어, 심신 이완',
    areas: ['gangneung-donghae-samcheok', 'sokcho-pyeongchang-resort'] },
  { slug: 'couple', name: '커플 관리', title: '커플 관리 안내｜동반 이용 프로그램', desc: '동반 방문 시 함께 이용할 수 있는 커플 관리 프로그램 안내.',
    intro: '커플 관리는 동반 방문 시 두 분이 함께 프로그램을 이용할 수 있도록 구성한 안내입니다. 숙소 객실 여건과 예약 가능 여부를 먼저 확인해야 하며, 리조트·펜션 이용 시 특히 사전 확인이 중요합니다.',
    good: '동반 방문, 여행·리조트 이용, 기념일 케어',
    areas: ['sokcho-pyeongchang-resort', 'gangneung-donghae-samcheok'] },
  { slug: 'night', name: '야간 예약', title: '야간 예약 안내｜야간 이용 전 확인 기준', desc: '야간 시간대 이용 전 건물 출입·이동 기준을 안내하는 야간 예약 안내.',
    intro: '야간 예약은 늦은 시간대 이용을 위한 안내로, 프로그램 자체보다 야간 건물 출입 가능 여부와 이동 기준이 핵심입니다. 호텔·오피스텔 야간 출입 정책과 예약자명 확인을 먼저 진행합니다.',
    good: '야간 이용, 늦은 체크인 숙소, 심야 이동',
    areas: ['daejeon-dunsan-yuseong', 'gwangju-sangmu-suwan'] },
];

// 이용 장소
const usePages = [
  { slug: 'home', name: '자택', desc: '자택 방문 전 주소·건물 출입·주차 등 확인 기준을 안내합니다.' },
  { slug: 'hotel', name: '호텔·숙소', desc: '호텔 프런트 확인, 예약자명, 객실 출입 정책 등 이용 기준 안내.' },
  { slug: 'officetel', name: '오피스텔', desc: '오피스텔 공동현관·엘리베이터 카드 등 출입 방식 확인 안내.' },
  { slug: 'apartment', name: '아파트 단지', desc: '아파트 단지 방문 전 동·호수, 공동현관 출입 확인 기준 안내.' },
  { slug: 'business-trip-accommodation', name: '출장 숙소', desc: '장기 출장 숙소 이용 전 예약자·출입·야간 기준 확인 안내.' },
  { slug: 'industrial-area', name: '산업단지', desc: '산업단지 인접 숙소 이동 거리와 출입 기준 확인 안내.' },
  { slug: 'innovation-city', name: '혁신도시', desc: '혁신도시 오피스텔·숙소 이용 전 출입·이동 기준 안내.' },
  { slug: 'tour-resort', name: '리조트', desc: '리조트 프런트 확인, 객실 출입 정책 등 이용 기준 안내.' },
  { slug: 'pension', name: '펜션', desc: '펜션·독채 숙소 위치와 진입로, 이동 기준 확인 안내.' },
  { slug: 'station-terminal', name: 'KTX·SRT 인접', desc: '역·터미널 인접 숙소 접근성과 이동 동선 확인 안내.' },
  { slug: 'night', name: '야간 예약', desc: '야간 시간대 건물 출입 가능 여부와 이동 기준 확인 안내.' },
  { slug: 'outer-area', name: '외곽 지역', desc: '외곽·산간 지역 이동 거리와 진입 기준 확인 안내.' },
];

// 예약 전 확인
const checkPages = [
  { slug: 'address', name: '주소 확인', desc: '정확한 방문 주소와 건물명 확인이 예약의 기본 기준입니다.' },
  { slug: 'building-access', name: '건물 출입', desc: '공동현관·엘리베이터 등 건물 출입 방식 확인 기준 안내.' },
  { slug: 'apartment-access', name: '아파트 출입', desc: '아파트 동·호수와 공동현관 출입 방식 확인 기준 안내.' },
  { slug: 'hotel-policy', name: '호텔 정책', desc: '호텔 프런트 확인, 예약자명, 방문 정책 확인 기준 안내.' },
  { slug: 'officetel-rule', name: '오피스텔 규정', desc: '오피스텔 공동현관·카드키 등 출입 규정 확인 안내.' },
  { slug: 'industrial-area', name: '산업단지 이동', desc: '산업단지 인접 숙소 이동 거리와 출입 기준 확인 안내.' },
  { slug: 'innovation-city', name: '혁신도시 이동', desc: '혁신도시 숙소 위치와 이동 동선 확인 기준 안내.' },
  { slug: 'resort-pension', name: '리조트·펜션', desc: '리조트·펜션 프런트 확인과 객실 출입 정책 안내.' },
  { slug: 'travel-fee', name: '이동 기준', desc: '지역·시간대·이동 거리에 따른 상담 기준 안내.' },
  { slug: 'night-access', name: '야간 출입', desc: '야간 시간대 건물 출입 가능 여부 확인 기준 안내.' },
  { slug: 'winter-road', name: '겨울철 도로', desc: '강원 산간·리조트권 겨울철 도로 상황 확인 안내.' },
  { slug: 'time', name: '예약 시간', desc: '예약 가능 시간대와 소요 시간 확인 기준 안내.' },
  { slug: 'change-policy', name: '변경 기준', desc: '예약 변경·취소 관련 기준을 안내합니다.' },
  { slug: 'privacy', name: '개인정보 처리', desc: '예약 확인에 필요한 최소 정보만 확인하는 처리 기준 안내.' },
  { slug: 'service-policy', name: '서비스 기준', desc: '제공 가능한 서비스 범위와 운영 기준 안내.' },
  { slug: 'customer-notice', name: '이용 안내', desc: '이용 전 반드시 확인해야 할 고객 안내사항입니다.' },
];

module.exports = { areas, regions, programs, usePages, checkPages };
