// ── 1차-B: 호남·강원 시·군의 핵심 생활권(life) 세부 페이지 ──
// 기존 25개 + 13개 = 핵심 생활권 38개. 각 도시의 실제 생활권을 고유하게 서술.

const lifeAreas = [
  { slug: 'jeonju-hanok-wansan', name: '전주 한옥마을·완산', region: 'honam', city: 'jeonju-si',
    title: '전주 한옥마을·완산 출장마사지｜관광 숙소 생활권 안내', desc: '전주 한옥마을·완산 도심 관광 숙소권 이용 전 확인 기준 안내.',
    feature: '한옥마을·완산은 전주 완산구의 관광·도심 생활권으로, 한옥마을 게스트하우스·한옥 스테이와 서신·중화산동 도심 상권이 이어집니다. 관광 성수기 숙소 수요가 크고 한옥 숙소는 출입 구조가 일반 건물과 달라 위치·객실 확인이 특히 중요합니다.',
    transport: 'KTX 전주역과 전주고속버스터미널에서 한옥마을까지 차량 이동이 이어지며, 도심 상권과 가깝습니다.',
    stay: '한옥마을 한옥 스테이·게스트하우스와 도심 비즈니스 숙소가 함께 있어 관광·업무 수요가 겹칩니다.',
    programs: ['aroma-therapy', 'thai-massage'], nearby: ['jeonju-deokjin-innovation'] },
  { slug: 'jeonju-deokjin-innovation', name: '전주 덕진·혁신도시', region: 'honam', city: 'jeonju-si',
    title: '전주 덕진·혁신도시 출장마사지｜대학·공공기관 생활권 안내', desc: '전주 덕진·혁신도시 대학가·공공기관 오피스텔 이용 기준 안내.',
    feature: '덕진·혁신도시는 전북대 대학가와 만성·중동 전주혁신도시가 이어지는 생활권입니다. 덕진동 대학가 원룸·상권과 혁신도시 신축 오피스텔·아파트가 함께 있어 이주 공공기관 근무자 수요가 큽니다.',
    transport: 'KTX 전주역이 덕진구에 있어 접근이 편리하고, 혁신도시는 서부 외곽에 위치합니다.',
    stay: '혁신도시 신축 오피스텔과 대학가 숙소가 있어 공공기관 출장·장기 체류 수요가 있습니다.',
    programs: ['thai-massage', 'sports-massage'], nearby: ['jeonju-hanok-wansan'] },
  { slug: 'iksan-station-yeongdeung', name: '익산역·영등', region: 'honam', city: 'iksan-si',
    title: '익산역·영등 출장마사지｜철도 분기 역세권 생활권 안내', desc: '익산역·영등동 철도 분기 역세권과 상권 숙소 이용 기준 안내.',
    feature: '익산역·영등은 호남·전라·장항선이 만나는 익산역세권과 영등동 신상권이 이어지는 생활권입니다. 환승 유동 인구가 많은 역세권 숙소와 영등동 아파트·상가가 함께 있어 출장·환승 수요가 집중됩니다.',
    transport: 'KTX·SRT 익산역이 호남 철도의 분기점이며, 영등동 상권과 익산공용버스터미널이 인접합니다.',
    stay: '익산역 인접 비즈니스 숙소와 영등동 상권 숙소가 많아 단기 체류 수요가 큽니다.',
    programs: ['sports-massage', 'foot-massage'], nearby: ['gunsan-susong-naun'] },
  { slug: 'gunsan-susong-naun', name: '군산 수송·나운', region: 'honam', city: 'gunsan-si',
    title: '군산 수송·나운 출장마사지｜신상권·주거 생활권 안내', desc: '군산 수송·나운동 신상권과 산단 인접 주거 생활권 이용 안내.',
    feature: '수송·나운은 군산의 신상권·주거 생활권으로, 수송동 대형 상권과 나운동 아파트 단지가 밀집해 있습니다. 군산국가산단과 가까워 산업 출장 수요와 주거 수요가 함께 있는 구역입니다.',
    transport: '군산역과 군산고속버스터미널이 축이며, 산단·근대문화거리는 차량 이동 동선을 확인합니다.',
    stay: '수송동 비즈니스 숙소와 산단 인접 출장 숙소가 있어 장기 체류 수요가 있습니다.',
    programs: ['sports-massage', 'deep-tissue'], nearby: ['iksan-station-yeongdeung'] },
  { slug: 'yeosu-expo-dolsan', name: '여수 엑스포·돌산', region: 'honam', city: 'yeosu-si',
    title: '여수 엑스포·돌산 출장마사지｜해안 관광 숙소 생활권 안내', desc: '여수 엑스포·돌산 해안 관광 리조트·호텔 이용 기준 안내.',
    feature: '엑스포·돌산은 여수의 대표 해안 관광 생활권으로, 여수엑스포역·오동도권과 돌산대교 건너 리조트·펜션권이 이어집니다. 성수기 해안 숙소 수요가 크고 돌산은 이동 동선이 별도라 위치 확인이 중요합니다.',
    transport: 'KTX 여수엑스포역과 여수종합버스터미널이 축이며, 돌산권은 돌산대교를 통한 이동 동선을 확인합니다.',
    stay: '엑스포·돌산 해안 리조트·호텔·펜션이 많아 계절 관광 숙박 수요가 뚜렷합니다.',
    programs: ['aroma-therapy', 'foot-massage'], nearby: ['suncheon-sindae-jorye'] },
  { slug: 'suncheon-sindae-jorye', name: '순천 신대·조례', region: 'honam', city: 'suncheon-si',
    title: '순천 신대·조례 출장마사지｜신도시·도심 생활권 안내', desc: '순천 신대지구·조례동 신도시·도심 상권 이용 기준 안내.',
    feature: '신대·조례는 순천의 신도시·도심 생활권으로, 율촌·해룡의 신대지구 신축 아파트·상권과 조례동 도심 상권이 이어집니다. 전남 동부의 생활 중심으로 신도시 오피스텔·아파트 수요가 빠르게 늘고 있습니다.',
    transport: '순천역과 순천종합버스터미널이 축이며, 신대지구는 동부 외곽에 위치합니다.',
    stay: '신대지구·도심 비즈니스 숙소와 순천만 관광 숙소가 있어 업무·관광 수요가 함께 있습니다.',
    programs: ['aroma-therapy', 'foot-massage'], nearby: ['yeosu-expo-dolsan', 'gwangyang-jungma-port'] },
  { slug: 'gwangyang-jungma-port', name: '광양 중마·광양항', region: 'honam', city: 'gwangyang-si',
    title: '광양 중마·광양항 출장마사지｜제철·항만 산업 생활권 안내', desc: '광양 중마동 신도심과 광양항·제철산단 출장 숙소 이용 안내.',
    feature: '중마·광양항은 광양의 산업·주거 생활권으로, 중마동 신도심 아파트·상권과 광양항·제철산단이 이어집니다. 제철·항만 출장 수요가 큰 구역으로 장기 체류 숙소 이용 기준이 중요합니다.',
    transport: '중마동 버스터미널과 KTX 순천역·광양항이 축이며, 산단은 차량 이동 동선을 확인합니다.',
    stay: '중마동 비즈니스 숙소와 산단 인접 출장 숙소가 많아 장기 체류 수요가 큽니다.',
    programs: ['sports-massage', 'deep-tissue'], nearby: ['suncheon-sindae-jorye'] },
  { slug: 'mokpo-hadang-namak', name: '목포 하당·남악', region: 'honam', city: 'mokpo-si',
    title: '목포 하당·남악 출장마사지｜신도심·행정 생활권 안내', desc: '목포 하당 신도심과 남악 전남도청 행정 신도시 이용 안내.',
    feature: '하당·남악은 목포권의 신도심·행정 생활권으로, 하당·상동 신도심 상권과 인접한 무안 남악·오룡 전남도청 신도시가 이어집니다. 해안 관광권과 달리 행정·주거·상업 수요가 중심입니다.',
    transport: 'KTX 목포역과 목포종합버스터미널, 남악 신도시가 축이며, 하당에서 남악까지 이동이 가깝습니다.',
    stay: '하당 비즈니스 숙소와 남악 신도시 숙소가 있어 행정·업무 출장 수요가 있습니다.',
    programs: ['aroma-therapy', 'swedish'], nearby: ['naju-bitgaram'] },
  { slug: 'naju-bitgaram', name: '나주 빛가람혁신도시', region: 'honam', city: 'naju-si',
    title: '나주 빛가람혁신도시 출장마사지｜공공기관 이전 생활권 안내', desc: '나주 빛가람 혁신도시 공공기관 이전권 오피스텔 이용 안내.',
    feature: '빛가람혁신도시는 나주 빛가람동의 공공기관 이전 생활권으로, 한전 등 이전 기관과 신축 오피스텔·아파트가 밀집해 있습니다. 광주와 생활권이 가까워 연계 이동이 많고 이주 근무자 수요가 큽니다.',
    transport: 'KTX 나주역과 혁신도시 간선도로가 축이며, 광주 도심과 이동이 가깝습니다.',
    stay: '혁신도시 신축 오피스텔·숙소가 많아 공공기관 출장·장기 체류 수요가 있습니다.',
    programs: ['aroma-therapy', 'sports-massage'], nearby: ['mokpo-hadang-namak'] },
  { slug: 'donghae-mukho-cheongok', name: '동해 묵호·천곡', region: 'gangwon', city: 'donghae-si',
    title: '동해 묵호·천곡 출장마사지｜항만·도심 생활권 안내', desc: '동해 묵호항 관광권과 천곡 도심·산업권 이용 기준 안내.',
    feature: '묵호·천곡은 동해의 관광·도심 생활권으로, 묵호항·논골담길 관광권과 천곡동 도심 상권, 북평 산업권이 이어집니다. 항만·산업 출장과 해안 관광 수요가 함께 있는 구역입니다.',
    transport: '동해역과 동해고속·시외버스터미널, 동해항이 축이며, 묵호·망상은 이동 동선을 확인합니다.',
    stay: '천곡 도심 숙소와 묵호·망상 해안 숙소, 산단 출장 숙소가 있습니다.',
    programs: ['sports-massage', 'foot-massage'], nearby: ['samcheok-beach-jeongna'] },
  { slug: 'samcheok-beach-jeongna', name: '삼척해변·정라', region: 'gangwon', city: 'samcheok-si',
    title: '삼척해변·정라 출장마사지｜해안 리조트 관광 생활권 안내', desc: '삼척해변·정라 도심과 쏠비치 해안 관광 숙소 이용 안내.',
    feature: '삼척해변·정라는 삼척의 해안 관광 생활권으로, 정라동 도심 상권과 삼척해변·이사부광장, 쏠비치 삼척 리조트권이 이어집니다. 해안 리조트 관광 수요가 크고 성수기 이동 기준이 중요합니다.',
    transport: '삼척종합버스터미널과 동해고속도로가 축이며, 인접한 동해역을 함께 이용합니다.',
    stay: '삼척해변·쏠비치 인접 관광 숙소와 도심 숙소가 있어 계절 관광 수요가 있습니다.',
    programs: ['aroma-therapy', 'lomi-lomi'], nearby: ['donghae-mukho-cheongok'] },
  { slug: 'hongcheon-vivaldi', name: '홍천 비발디파크', region: 'gangwon', city: 'hongcheon-gun',
    title: '홍천 비발디파크 출장마사지｜리조트·펜션 숙소 생활권 안내', desc: '홍천 비발디파크 리조트·펜션 외곽 숙소 이용 기준 안내.',
    feature: '비발디파크권은 홍천의 대표 리조트·펜션 생활권으로, 비발디파크·오션월드 리조트와 서면·팔봉 펜션·전원 숙소가 흩어져 있습니다. 도심보다 리조트·독채 숙소가 중심이라 위치와 진입로 확인이 특히 중요합니다.',
    transport: '홍천종합버스터미널과 중앙고속도로가 축이며, 철도가 없어 차량 이동 기준이 중요합니다.',
    stay: '비발디파크 리조트와 서면·팔봉 펜션이 많아 리조트·독채 숙소 이용 기준을 우선 확인합니다.',
    programs: ['thai-massage', 'couple'], nearby: ['chuncheon-onui-toegye'] },
  { slug: 'goseong-hwajinpo-geojin', name: '고성 화진포·거진', region: 'gangwon', city: 'goseong-gun',
    title: '고성 화진포·거진 출장마사지｜최북단 해안 관광 생활권 안내', desc: '고성 화진포·거진 해안 관광 펜션·리조트 이용 기준 안내.',
    feature: '화진포·거진은 강원 최북단 고성의 해안 관광 생활권으로, 화진포 석호·해변과 거진항, 대진 해안이 이어집니다. 해변을 따라 펜션·리조트가 흩어져 있고 통일전망대 안보 관광권과도 가깝습니다.',
    transport: '간성·거진 버스터미널과 동해대로가 축이며, 해변·전망대권은 이동 거리를 확인합니다.',
    stay: '화진포·거진 해안 펜션·리조트가 많아 계절 해양 관광 숙박 수요가 있습니다.',
    programs: ['aroma-therapy', 'lomi-lomi'], nearby: [] },
];

module.exports = { lifeAreas };
