// ── 역·터미널·KTX·SRT 거점 페이지 & 산업/혁신/관광 특화 use 페이지 ──
// 출구별·노선별 페이지는 만들지 않습니다(도어웨이 방지). 거점 단위로만 안내.

const stations = [
  // 천안
  { slug: 'cheonan-asan-station', name: '천안아산역', region: 'cheonan', lines: 'KTX · SRT · 수도권 전철',
    title: '천안아산역 출장마사지｜KTX·SRT 거점 숙소 안내', desc: '천안아산역 KTX·SRT 환승 거점 인접 호텔·오피스텔 이용 안내.',
    context: '천안아산역은 KTX·SRT가 함께 정차하는 광역 환승 거점으로, 역세권 비즈니스 호텔과 신축 오피스텔이 이어집니다. 아산 배방·탕정과 천안 불당 생활권 사이에 있어 출장·환승 수요가 집중됩니다.',
    programs: ['swedish', 'aroma-therapy'], nearby: ['cheonan-buldang-ssangyong'] },
  { slug: 'cheonan-station', name: '천안역', region: 'cheonan', lines: '경부선 · 장항선 · 수도권 전철 1호선',
    title: '천안역 출장마사지｜원도심 역세권 숙소 안내', desc: '천안역 경부·장항선 역세권과 원도심 상권 숙소 이용 안내.',
    context: '천안역은 경부선·장항선과 수도권 전철 1호선이 지나는 원도심 관문으로, 동부 원도심 상권과 서부 대학가가 이어집니다. 시내 접근이 편리한 도심 역세권입니다.',
    programs: ['foot-massage', 'thai-massage'], nearby: ['cheonan-dujeong-seongjeong'] },
  { slug: 'dujeong-station', name: '두정역', region: 'cheonan', lines: '경부선 · 수도권 전철 1호선',
    title: '두정역 출장마사지｜상권·역세권 숙소 안내', desc: '두정역 상권과 대형마트·터미널 인접 역세권 숙소 이용 안내.',
    context: '두정역은 두정동 먹자상권과 대형마트, 천안종합버스터미널 인접권을 낀 역세권으로, 오피스텔과 상가 숙소가 이어집니다.',
    programs: ['foot-massage', 'sports-massage'], nearby: ['cheonan-dujeong-seongjeong'] },
  { slug: 'cheonan-terminal', name: '천안종합터미널', region: 'cheonan', lines: '고속버스 · 시외버스',
    title: '천안종합터미널 출장마사지｜신부동 교통 거점 안내', desc: '천안종합버스터미널 신부동 상권 인접 숙소 이용 기준 안내.',
    context: '천안종합버스터미널은 신부동 상권과 백화점을 낀 시외·고속 교통 중심으로, 유동 인구가 많고 터미널 인접 비즈니스 숙소가 이어집니다.',
    programs: ['sports-massage', 'foot-massage'], nearby: ['cheonan-sinbu-terminal'] },
  // 대전
  { slug: 'daejeon-station', name: '대전역', region: 'daejeon', lines: 'KTX · 경부선 · 도시철도 1호선',
    title: '대전역 출장마사지｜KTX 거점 역세권 숙소 안내', desc: '대전역 KTX·동부터미널 거점 인접 비즈니스 숙소 이용 안내.',
    context: '대전역은 KTX와 동부시외버스터미널을 낀 대전의 관문으로, 역세권 비즈니스 호텔과 원도심 상권이 이어집니다. 환승·단기 출장 수요가 집중됩니다.',
    programs: ['foot-massage', 'deep-tissue'], nearby: ['daejeon-station-yongjeon'] },
  { slug: 'seodaejeon-station', name: '서대전역', region: 'daejeon', lines: '호남선 · KTX 일부',
    title: '서대전역 출장마사지｜중구 원도심 역세권 안내', desc: '서대전역 중구 원도심 인접 역세권 숙소 이용 기준 안내.',
    context: '서대전역은 호남선과 일부 KTX가 정차하는 중구 원도심 관문으로, 은행·대흥 원도심 상권과 인접해 도심 접근이 편리합니다.',
    programs: ['foot-massage', 'thai-massage'], nearby: ['daejeon-eunhaeng-daeheung'] },
  { slug: 'yuseong-terminal', name: '유성고속버스터미널', region: 'daejeon', lines: '고속버스 · 도시철도 유성온천역',
    title: '유성터미널 출장마사지｜온천 호텔가 거점 안내', desc: '유성고속버스터미널·유성온천 호텔가 인접 숙소 이용 안내.',
    context: '유성고속버스터미널은 유성온천 호텔가와 인접한 교통 거점으로, 온천 관광 숙소와 대학가 접근이 편리합니다.',
    programs: ['aroma-therapy', 'swedish'], nearby: ['yuseong-bongmyeong'] },
  { slug: 'dunsan-government-complex', name: '정부대전청사', region: 'daejeon', lines: '도시철도 정부청사역',
    title: '정부청사 출장마사지｜둔산 업무지구 거점 안내', desc: '정부대전청사·둔산 업무지구 오피스 인접 숙소 이용 안내.',
    context: '정부대전청사 일대는 둔산 업무지구의 중심으로, 관공서·오피스와 비즈니스 호텔이 밀집한 평일 업무 수요가 큰 거점입니다.',
    programs: ['sports-massage', 'aroma-therapy'], nearby: ['daejeon-dunsan-tanbang'] },
  // 호남
  { slug: 'gwangju-songjeong-station', name: '광주송정역', region: 'honam', lines: 'KTX · SRT · 호남선',
    title: '광주송정역 출장마사지｜KTX 호남선 거점 안내', desc: '광주송정역 KTX·SRT 호남 관문 인접 숙소 이용 기준 안내.',
    context: '광주송정역은 호남선 KTX·SRT의 관문으로, 광산구 송정 원도심 상권과 역세권 비즈니스 숙소가 이어집니다. 환승·출장 수요가 집중됩니다.',
    programs: ['foot-massage', 'aroma-therapy'], nearby: ['gwangju-songjeong-station'] },
  { slug: 'gwangju-terminal', name: '광주종합터미널(유스퀘어)', region: 'honam', lines: '고속버스 · 시외버스',
    title: '광주터미널 출장마사지｜유스퀘어 광천 거점 안내', desc: '광주종합버스터미널 유스퀘어·상무 인접 숙소 이용 안내.',
    context: '광주종합버스터미널(유스퀘어)은 광천동 복합상권을 낀 교통 중심으로, 상무지구 업무권과 인접해 유동 인구가 큽니다.',
    programs: ['aroma-therapy', 'swedish'], nearby: ['gwangju-sangmu-gwangcheon'] },
  { slug: 'jeonju-station', name: '전주역', region: 'honam', lines: 'KTX · 전라선',
    title: '전주역 출장마사지｜덕진 역세권 거점 안내', desc: '전주역 전라선 덕진구 역세권과 도심 숙소 이용 기준 안내.',
    context: '전주역은 전라선 KTX가 정차하는 덕진구 관문으로, 역세권 숙소와 도심·한옥마을 접근이 이어집니다.',
    programs: ['thai-massage', 'aroma-therapy'], nearby: [] },
  { slug: 'iksan-station', name: '익산역', region: 'honam', lines: 'KTX · SRT · 호남선 · 전라선 · 장항선',
    title: '익산역 출장마사지｜호남 철도 분기 거점 안내', desc: '익산역 KTX·SRT 호남 철도 분기점 인접 숙소 이용 안내.',
    context: '익산역은 호남선·전라선·장항선이 만나는 호남 철도의 분기점으로, 역세권 비즈니스 숙소와 영등동 상권이 이어집니다. 환승 유동 인구가 큽니다.',
    programs: ['sports-massage', 'foot-massage'], nearby: [] },
  { slug: 'gunsan-station', name: '군산역', region: 'honam', lines: '장항선',
    title: '군산역 출장마사지｜군산 산단·도심 거점 안내', desc: '군산역 장항선과 군산산단·도심 인접 숙소 이용 기준 안내.',
    context: '군산역은 장항선 관문으로, 수송동 신상권과 군산국가산단, 근대문화거리 관광권 이동의 거점입니다.',
    programs: ['sports-massage', 'deep-tissue'], nearby: [] },
  { slug: 'yeosu-expo-station', name: '여수엑스포역', region: 'honam', lines: 'KTX · 전라선',
    title: '여수엑스포역 출장마사지｜해안 관광 거점 안내', desc: '여수엑스포역 전라선 해안 관광권·도심 숙소 이용 안내.',
    context: '여수엑스포역은 전라선 KTX의 종착 관문으로, 엑스포·오동도 해안 관광권과 도심 숙소 접근의 거점입니다.',
    programs: ['foot-massage', 'aroma-therapy'], nearby: [] },
  { slug: 'suncheon-station', name: '순천역', region: 'honam', lines: 'KTX · 전라선 · 경전선',
    title: '순천역 출장마사지｜전남 동부 철도 거점 안내', desc: '순천역 전라·경전선 도심·신대지구 인접 숙소 이용 안내.',
    context: '순천역은 전라선·경전선이 만나는 전남 동부의 철도 중심으로, 도심 상권과 신대지구, 순천만 관광권 이동의 거점입니다.',
    programs: ['aroma-therapy', 'foot-massage'], nearby: [] },
  { slug: 'mokpo-station', name: '목포역', region: 'honam', lines: 'KTX · 호남선',
    title: '목포역 출장마사지｜서남권 종착 거점 안내', desc: '목포역 호남선 종착 원도심·하당 인접 숙소 이용 기준 안내.',
    context: '목포역은 호남선 KTX의 종착 관문으로, 유달산 원도심과 하당 신도심, 남악 신도시 이동의 거점입니다.',
    programs: ['aroma-therapy', 'swedish'], nearby: [] },
  // 강원
  { slug: 'chuncheon-station', name: '춘천역', region: 'gangwon', lines: 'ITX-청춘 · 경춘선',
    title: '춘천역 출장마사지｜원도심 역세권 거점 안내', desc: '춘천역 경춘선 명동·중앙로 원도심 인접 숙소 이용 안내.',
    context: '춘천역은 경춘선·ITX-청춘의 관문으로, 명동·중앙로 원도심 상권과 소양강 관광권 접근의 거점입니다.',
    programs: ['sports-massage', 'thai-massage'], nearby: ['chuncheon-myeongdong-jungangro'] },
  { slug: 'namchuncheon-station', name: '남춘천역', region: 'gangwon', lines: 'ITX-청춘 · 경춘선',
    title: '남춘천역 출장마사지｜온의·신주거 거점 안내', desc: '남춘천역 온의·퇴계 신주거권 인접 숙소 이용 기준 안내.',
    context: '남춘천역은 온의·퇴계 신주거권과 시외버스터미널을 낀 거점으로, 신축 오피스텔과 상권이 이어져 업무·출장 수요가 늘고 있습니다.',
    programs: ['thai-massage', 'sports-massage'], nearby: ['chuncheon-onui-toegye'] },
  { slug: 'wonju-station', name: '원주역', region: 'gangwon', lines: 'KTX · 중앙선',
    title: '원주역 출장마사지｜만종 KTX 거점 안내', desc: '원주역(만종) KTX 중앙선 도심·혁신도시 이동 거점 안내.',
    context: '원주역(만종)은 중앙선 KTX의 관문으로, 무실 도심과 반곡 혁신도시, 기업도시 이동의 거점입니다.',
    programs: ['sports-massage', 'thai-massage'], nearby: ['wonju-musil-dangye'] },
  { slug: 'gangneung-station', name: '강릉역', region: 'gangwon', lines: 'KTX · 경강선',
    title: '강릉역 출장마사지｜동해안 관광 관문 거점 안내', desc: '강릉역 KTX 경강선 도심·경포 해안 이동 거점 안내.',
    context: '강릉역은 경강선 KTX의 동해안 관문으로, 교동 도심과 경포·안목 해안 관광권 이동의 거점입니다. 성수기 관광 유동 인구가 큽니다.',
    programs: ['aroma-therapy', 'foot-massage'], nearby: ['gangneung-gyeongpo-anmok'] },
  { slug: 'sokcho-terminal', name: '속초고속버스터미널', region: 'gangwon', lines: '고속버스 · 시외버스',
    title: '속초터미널 출장마사지｜해안 관광 거점 안내', desc: '속초고속버스터미널 도심·해변 관광 숙소 이동 거점 안내.',
    context: '속초는 철도가 없어 속초고속·시외버스터미널이 교통 중심입니다. 도심 조양·교동 상권과 속초해변 관광 숙소 이동의 거점입니다.',
    programs: ['aroma-therapy', 'couple'], nearby: ['sokcho-joyang-gyodong'] },
  { slug: 'pyeongchang-station', name: '평창역', region: 'gangwon', lines: 'KTX · 경강선',
    title: '평창역 출장마사지｜산악 관광 거점 안내', desc: '평창역 경강선 KTX 리조트·산악 관광권 이동 거점 안내.',
    context: '평창역은 경강선 KTX가 정차하는 산악 관광 관문으로, 평창읍과 대관령 리조트권 이동의 거점입니다.',
    programs: ['aroma-therapy', 'couple'], nearby: ['pyeongchang-daegwallyeong-yongpyong'] },
  { slug: 'jinbu-station', name: '진부(오대산)역', region: 'gangwon', lines: 'KTX · 경강선',
    title: '진부역 출장마사지｜오대산·용평 관문 거점 안내', desc: '진부(오대산)역 경강선 용평·오대산 리조트 이동 거점 안내.',
    context: '진부(오대산)역은 경강선 KTX의 대관령 관문으로, 용평·알펜시아 리조트권과 오대산 관광권 이동의 거점입니다. 겨울철 도로 상황 확인이 중요합니다.',
    programs: ['aroma-therapy', 'couple'], nearby: ['pyeongchang-daegwallyeong-yongpyong'] },
];

// 산업단지·혁신도시·관광 숙소 특화 use 페이지 (/use/*)
const useSpecial = [
  { slug: 'cheonan-asan-station-stay', name: '천안아산역 출장 숙소', kind: 'industry',
    title: '천안아산역 출장 숙소 안내｜KTX·SRT 체류 기준', desc: '천안아산역 KTX·SRT 인접 출장 숙소 예약·출입 기준 안내.',
    body: '천안아산역 일대는 KTX·SRT 환승과 아산 탕정·배방 산업권 출장 수요가 겹치는 구역입니다. 역세권 비즈니스 호텔·레지던스 이용 시 예약자명, 프런트 확인, 야간 출입 정책을 먼저 확인해야 합니다.' },
  { slug: 'daedeok-research-area', name: '대덕연구단지 출장', kind: 'industry',
    title: '대덕연구단지 출장 안내｜유성·연구단지 체류 기준', desc: '대덕특구 연구단지 인접 유성·봉명 숙소 이용 기준 안내.',
    body: '대덕연구개발특구는 유성구 일대의 연구소·기업이 밀집한 구역으로, 인접한 유성온천·봉명 호텔가를 출장 숙소로 이용하는 경우가 많습니다. 연구단지 방문 시 이동 동선과 숙소 출입 기준을 확인하세요.' },
  { slug: 'sejong-nearby-link', name: '세종 인접 이동', kind: 'industry',
    title: '세종 인접 이동 안내｜대전 도안·유성 연계 기준', desc: '세종 인접 대전 도안·유성 생활권 연계 이동 기준 안내.',
    body: '세종특별자치시는 대전 도안·유성과 생활권이 가깝게 이어지는 구역입니다. 본 사이트는 대전 생활권을 중심으로 안내하며, 세종 인접 이동 시 실제 주소와 이동 거리를 먼저 확인합니다.' },
  { slug: 'jeonju-innovation-city', name: '전주혁신도시', kind: 'industry',
    title: '전주혁신도시 출장 안내｜만성·중동 오피스텔 기준', desc: '전주혁신도시 만성·중동 공공기관·오피스텔 이용 기준 안내.',
    body: '전주혁신도시는 전주 덕진구 만성·중동 일대에 공공기관이 이전한 구역으로, 신축 오피스텔·아파트가 밀집해 있습니다. 도심에서 서부로 떨어져 있어 이동 동선과 건물 출입 방식을 확인하세요.' },
  { slug: 'naju-innovation-city', name: '나주 빛가람혁신도시', kind: 'industry',
    title: '나주 빛가람혁신도시 출장 안내｜공공기관 이전권 기준', desc: '나주 빛가람 혁신도시 공공기관 이전권 오피스텔 이용 안내.',
    body: '나주 빛가람혁신도시는 한전 등 공공기관이 이전한 구역으로, 신축 오피스텔과 아파트가 밀집해 있습니다. 광주와 생활권이 가까워 연계 이동이 많으며, 건물 출입 방식 확인이 중요합니다.' },
  { slug: 'yeosu-industrial-area', name: '여수산단 출장', kind: 'industry',
    title: '여수산단 출장 안내｜여수국가산단 체류 기준', desc: '여수국가산업단지 인접 출장 숙소 이동·출입 기준 안내.',
    body: '여수국가산업단지는 화학·정유 기업이 밀집한 구역으로, 산단 출장 수요와 여수 해안 관광 숙소가 나뉩니다. 산단 인접 출장 숙소 이용 시 이동 거리와 야간 출입 기준을 확인하세요.' },
  { slug: 'gwangyang-port-industrial', name: '광양항·제철산단', kind: 'industry',
    title: '광양항·제철산단 출장 안내｜중마 체류 기준', desc: '광양항·제철산단 인접 중마동 출장 숙소 이용 기준 안내.',
    body: '광양항과 광양제철소·산단은 항만·제철 출장 수요가 큰 구역입니다. 인접한 중마동 비즈니스 숙소를 출장 숙소로 이용하는 경우가 많으며, 산단 이동 동선과 장기 체류 기준을 확인하세요.' },
  { slug: 'gunsan-saemangeum-industrial', name: '군산·새만금 산단', kind: 'industry',
    title: '군산·새만금 산단 출장 안내｜장기 체류 기준', desc: '군산산단·새만금 개발권 인접 출장 숙소 이용 기준 안내.',
    body: '군산국가산단과 새만금 개발권은 산업 출장 수요가 큰 구역으로, 수송동 신상권과 산단 인접 숙소가 출장 거점이 됩니다. 새만금은 이동 거리가 있어 위치와 장기 체류 기준을 확인하세요.' },
  // 강원 관광 숙소
  { slug: 'gangneung-beach-stay', name: '강릉 해변 숙소', kind: 'resort',
    title: '강릉 해변 숙소 안내｜경포·안목 관광 숙소 기준', desc: '강릉 경포·안목 해변 리조트·호텔 관광 숙소 이용 기준 안내.',
    body: '강릉 경포·안목 해변은 리조트·호텔·펜션이 밀집한 관광 숙소권입니다. 성수기 프런트 확인, 객실 출입 정책, 예약자명, 이동 동선을 먼저 확인해야 합니다.' },
  { slug: 'sokcho-beach-daepo-stay', name: '속초 해변·대포 숙소', kind: 'resort',
    title: '속초 해변·대포 숙소 안내｜해안 관광 숙소 기준', desc: '속초해변·대포항 해안 리조트·펜션 관광 숙소 이용 안내.',
    body: '속초해변·대포항 일대는 해안 리조트·호텔·펜션이 밀집한 관광 숙소권입니다. 성수기 객실 출입 정책과 프런트 확인, 이동 동선을 먼저 확인하세요.' },
  { slug: 'yangyang-surf-beach-stay', name: '양양 서핑 해변 숙소', kind: 'resort',
    title: '양양 서핑 해변 숙소 안내｜인구·서피비치 기준', desc: '양양 낙산·인구 서피비치 서핑 관광 숙소 이용 기준 안내.',
    body: '양양 낙산·인구 해변은 서핑 관광 숙소와 게스트하우스·펜션이 흩어진 구역입니다. 해변별 위치와 진입로, 객실 출입 기준을 예약 전에 확인하세요.' },
  { slug: 'pyeongchang-resort', name: '평창 리조트', kind: 'resort',
    title: '평창 리조트 안내｜용평·알펜시아·휘닉스 기준', desc: '평창 용평·알펜시아·휘닉스 리조트 객실 이용 기준 안내.',
    body: '평창 대관령 용평·알펜시아·휘닉스파크는 스키·산악 리조트 숙소권입니다. 리조트 콘도·호텔 객실 출입 정책과 프런트 확인, 겨울철 도로 상황을 먼저 확인하세요.' },
  { slug: 'high1-resort-stay', name: '하이원리조트 숙소', kind: 'resort',
    title: '하이원리조트 숙소 안내｜사북·고한 리조트 기준', desc: '정선 하이원리조트 콘도·호텔 객실 이용 기준 안내.',
    body: '정선 하이원리조트는 사북·고한의 산악 리조트 숙소권으로, 콘도·호텔 객실 출입 정책과 프런트 확인, 산간 겨울철 이동 기준을 먼저 확인해야 합니다.' },
  { slug: 'vivaldi-park-stay', name: '비발디파크 숙소', kind: 'resort',
    title: '비발디파크 숙소 안내｜홍천 리조트 이용 기준', desc: '홍천 비발디파크 리조트·콘도 객실 이용 기준 안내.',
    body: '홍천 비발디파크는 스키·오션월드를 낀 리조트 숙소권으로, 콘도·호텔 객실 출입 정책과 프런트 확인, 외곽 이동 동선을 먼저 확인하세요.' },
  { slug: 'pension-private-stay', name: '펜션·독채 숙소', kind: 'resort',
    title: '펜션·독채 숙소 안내｜강원 외곽 숙소 이용 기준', desc: '강원 펜션·독채 숙소 위치·진입로·이용 기준 안내.',
    body: '강원 산악·해안권 펜션·독채 숙소는 위치가 외곽에 흩어져 있어 정확한 주소와 진입로, 예약자명, 야간 이동 기준 확인이 특히 중요합니다.' },
  { slug: 'winter-road-check', name: '겨울철 도로 확인', kind: 'resort',
    title: '겨울철 도로 확인 안내｜강원 산간 이동 기준', desc: '강원 산간·리조트권 겨울철 도로·이동 기준 확인 안내.',
    body: '강원 산간·리조트권은 겨울철 적설·결빙으로 이동 시간이 크게 달라집니다. 리조트·펜션 방문 전 도로 상황과 이동 기준을 미리 확인해야 안내가 원활합니다.' },
];

module.exports = { stations, useSpecial };
