// ── 핵심 생활권(life) 페이지 데이터 ──
// 각 생활권의 실제 특징·교통·숙소를 고유하게 서술합니다.
// region: 권역 slug, city: 상위 시·군 slug (브레드크럼/내부링크용)

const lifeAreas = [
  // ── 천안 ──
  { slug: 'cheonan-buldang-ssangyong', name: '천안 불당·쌍용', region: 'cheonan', city: 'seobuk-gu',
    title: '천안 불당·쌍용 출장마사지｜신도시 오피스텔 생활권 안내', desc: '천안 불당·쌍용 신도시 오피스텔·아파트 이용 전 출입 기준 안내.',
    feature: '불당·쌍용은 천안 서북구의 대표 신도시 생활권으로, 불당지구의 고층 오피스텔·주상복합과 쌍용동 아파트 단지가 밀집해 있습니다. 신축 건물이 많아 공동현관·엘리베이터 보안 절차가 건물마다 달라 출입 방식 확인이 특히 중요합니다.',
    transport: '천안아산역까지 차량 이동이 짧고, 불당동에서 두정·터미널 방면 접근도 편리합니다.',
    stay: '불당 오피스텔·레지던스가 많아 출장·단기 체류 수요가 높은 구역입니다.',
    programs: ['swedish', 'aroma-therapy'], nearby: ['cheonan-dujeong-seongjeong', 'cheonan-asan-station'] },
  { slug: 'cheonan-dujeong-seongjeong', name: '천안 두정·성정', region: 'cheonan', city: 'seobuk-gu',
    title: '천안 두정·성정 출장마사지｜상권·비즈니스 숙소 생활권 안내', desc: '천안 두정·성정 상권과 두정역 인접 비즈니스 숙소 이용 안내.',
    feature: '두정·성정은 두정역과 대형마트, 먹자상권이 이어지는 천안 서북구의 상업 생활권입니다. 두정동은 역세권 오피스텔과 상가, 성정동은 오래된 주거·상업지가 섞여 있어 신축과 구축 건물 출입 방식이 함께 존재합니다.',
    transport: '두정역(경부선)과 천안종합버스터미널이 인접해 시내·시외 접근성이 좋습니다.',
    stay: '두정역 인접 비즈니스 숙소와 상권 숙소가 있어 단기 방문 수요가 이어집니다.',
    programs: ['thai-massage', 'foot-massage'], nearby: ['cheonan-buldang-ssangyong', 'cheonan-sinbu-terminal'] },
  { slug: 'cheonan-sinbu-terminal', name: '천안 신부·터미널', region: 'cheonan', city: 'dongnam-gu',
    title: '천안 신부·터미널 출장마사지｜교통 중심 생활권 안내', desc: '천안 신부동 종합터미널 상권과 역세권 교통 생활권 이용 안내.',
    feature: '신부동은 천안종합버스터미널과 백화점, 유흥·먹자상권이 밀집한 동남구의 교통·상업 중심입니다. 유동 인구가 많고 상가 건물과 오피스텔이 섞여 있어 예약 시 정확한 건물명과 출입 방식 확인이 중요합니다.',
    transport: '천안종합버스터미널(고속·시외)과 천안역이 가까워 시외 교통 접근성이 가장 좋습니다.',
    stay: '터미널 인접 비즈니스 호텔과 상권 숙소가 많아 단기·환승 수요가 큽니다.',
    programs: ['foot-massage', 'sports-massage'], nearby: ['cheonan-dujeong-seongjeong', 'cheonan-asan-station'] },
  { slug: 'cheonan-asan-station', name: '천안아산역', region: 'cheonan', city: 'seobuk-gu',
    title: '천안아산역 출장마사지｜KTX·SRT 역세권 숙소 안내', desc: '천안아산역 KTX·SRT 인접 호텔·오피스텔 출장 숙소 이용 안내.',
    feature: '천안아산역은 KTX·SRT가 정차하는 광역 환승 거점으로, 역세권 신축 오피스텔과 비즈니스 호텔이 이어집니다. 아산 배방·탕정과 천안 불당 생활권 사이에 위치해 출장·환승 수요가 집중되는 구역입니다.',
    transport: 'KTX·SRT 천안아산역과 수도권 전철 아산역이 연결되어 서울·수도권 접근이 빠릅니다.',
    stay: '역 인접 비즈니스 호텔·레지던스가 많아 출장 체류 수요가 가장 높습니다.',
    programs: ['swedish', 'aroma-therapy'], nearby: ['cheonan-buldang-ssangyong', 'cheonan-sinbu-terminal'] },
  { slug: 'seonghwan-jiksan', name: '천안 성환·직산', region: 'cheonan', city: 'seobuk-gu',
    title: '천안 성환·직산 출장마사지｜북부 산업·역세권 안내', desc: '천안 성환·직산 북부 산업·물류권과 역세권 이동 기준 안내.',
    feature: '성환·직산은 천안 북부의 산업·물류·역세권 생활권입니다. 성환역·직산역 주변 주거지와 물류·제조 산업권, 대학 캠퍼스가 있어 도심과 떨어진 외곽 이동 기준이 중요합니다.',
    transport: '성환역·직산역(경부선)과 국도가 축이며, 평택·아산 방면 이동이 이어집니다.',
    stay: '역세권 소규모 숙소와 산업권 출장 숙소가 있어 공단 방문 수요가 있습니다.',
    programs: ['sports-massage', 'foot-massage'], nearby: ['cheonan-asan-station', 'cheonan-dujeong-seongjeong'] },

  // ── 대전 ──
  { slug: 'daejeon-dunsan-tanbang', name: '대전 둔산·탄방', region: 'daejeon', city: 'seo-gu',
    title: '대전 둔산·탄방 출장마사지｜업무지구 생활권 안내', desc: '대전 둔산·탄방 정부청사·오피스 업무지구 이용 기준 안내.',
    feature: '둔산·탄방은 정부대전청사와 법원·검찰, 대형 오피스가 밀집한 대전의 업무 중심 생활권입니다. 둔산동 오피스와 탄방동 아파트·상가가 이어지며, 평일 업무 수요와 저녁 상권이 뚜렷합니다.',
    transport: '지하철 정부청사역·시청역·탄방역이 지나며, 대전역·유성 이동이 편리합니다.',
    stay: '둔산 비즈니스 호텔과 탄방 오피스텔이 많아 업무 출장 체류가 많습니다.',
    programs: ['sports-massage', 'aroma-therapy'], nearby: ['doan-gwanjeo', 'yuseong-bongmyeong'] },
  { slug: 'yuseong-bongmyeong', name: '대전 유성·봉명', region: 'daejeon', city: 'yuseong-gu',
    title: '대전 유성·봉명 출장마사지｜온천 호텔·대학가 생활권 안내', desc: '대전 유성온천·봉명 호텔가와 궁동 대학가 이용 기준 안내.',
    feature: '유성·봉명은 유성온천 관광특구의 호텔가와 봉명동 숙박·상업지, 인근 궁동 대학가가 이어지는 대전의 숙박 중심 생활권입니다. 호텔·레지던스가 밀집해 관광·비즈니스 숙박 수요가 가장 높습니다.',
    transport: '지하철 유성온천역과 유성고속버스터미널이 있어 호텔·대학가 접근이 편리합니다.',
    stay: '유성온천 호텔과 봉명 숙소가 밀집해 프런트·객실 출입 정책 확인이 특히 중요합니다.',
    programs: ['aroma-therapy', 'swedish'], nearby: ['daejeon-dunsan-tanbang', 'doan-gwanjeo'] },
  { slug: 'daejeon-station-yongjeon', name: '대전역·용전', region: 'daejeon', city: 'dong-gu',
    title: '대전역·용전 출장마사지｜KTX 역세권 생활권 안내', desc: '대전역·용전 KTX·동부터미널 역세권 숙소 이용 기준 안내.',
    feature: '대전역·용전은 KTX 대전역과 동부시외버스터미널을 낀 교통 중심 생활권입니다. 역세권 비즈니스 숙소와 원도심 상권, 용전동 터미널권이 이어져 환승·단기 출장 유동 인구가 큽니다.',
    transport: 'KTX 대전역과 동부시외버스터미널, 지하철 대전역이 축으로 교통 접근성이 가장 좋습니다.',
    stay: '역 인접 비즈니스 호텔이 많아 환승·단기 출장 숙박 수요가 집중됩니다.',
    programs: ['foot-massage', 'deep-tissue'], nearby: ['daejeon-eunhaeng-daeheung', 'daedeok-sinchangjin'] },
  { slug: 'daejeon-eunhaeng-daeheung', name: '대전 은행·대흥', region: 'daejeon', city: 'jung-gu',
    title: '대전 은행·대흥 출장마사지｜원도심 상권 생활권 안내', desc: '대전 은행·대흥 으능정이 원도심 상권 이용 기준 안내.',
    feature: '은행·대흥은 으능정이거리와 중앙로를 중심으로 한 대전 중구의 전통 원도심 생활권입니다. 오래된 상권과 근린 주거, 소규모 오피스가 밀집해 있어 구축 건물 출입 방식 확인이 필요합니다.',
    transport: '지하철 중앙로역·중구청역과 서대전역이 인접해 도심 이동이 편리합니다.',
    stay: '원도심 비즈니스 숙소와 상권 숙소가 있어 도심 근거리 방문 수요가 이어집니다.',
    programs: ['foot-massage', 'thai-massage'], nearby: ['daejeon-station-yongjeon', 'daejeon-dunsan-tanbang'] },
  { slug: 'doan-gwanjeo', name: '대전 도안·관저', region: 'daejeon', city: 'seo-gu',
    title: '대전 도안·관저 출장마사지｜신도시 아파트 생활권 안내', desc: '대전 도안·관저 신도시 아파트 단지 출입 기준 안내.',
    feature: '도안·관저는 서구 남부의 신도시 아파트 생활권으로, 도안신도시의 신축 아파트 단지와 관저동 주거지가 이어집니다. 대단지 아파트가 많아 동·호수와 공동현관 출입 확인이 중요합니다.',
    transport: '도안대로·서대전IC가 축이며, 둔산·유성 방면 이동이 편리합니다.',
    stay: '단지형 주거가 중심으로, 인접 둔산·유성 숙소와 연계 이동이 많습니다.',
    programs: ['thai-massage', 'sports-massage'], nearby: ['daejeon-dunsan-tanbang', 'yuseong-bongmyeong'] },
  { slug: 'daedeok-sinchangjin', name: '대전 대덕·신탄진', region: 'daejeon', city: 'daedeok-gu',
    title: '대전 대덕·신탄진 출장마사지｜북부 주거·산업 생활권 안내', desc: '대전 대덕·신탄진 북부 주거·산업권 이동 기준 안내.',
    feature: '대덕·신탄진은 대전 북부의 주거·산업 생활권으로, 송촌·중리 주거지와 신탄진 북부 생활권, 대덕산업단지가 이어집니다. 도심에서 북쪽으로 떨어져 있어 이동 동선과 산단 출입 기준 확인이 중요합니다.',
    transport: '신탄진역과 신탄진IC가 축이며, 회덕·오정에서 대전역·둔산 이동이 이어집니다.',
    stay: '신탄진 인접 숙소와 산업단지 출장 숙소가 있어 공단 방문 수요가 있습니다.',
    programs: ['sports-massage', 'deep-tissue'], nearby: ['daejeon-station-yongjeon', 'daejeon-dunsan-tanbang'] },

  // ── 광주 ──
  { slug: 'gwangju-sangmu-gwangcheon', name: '광주 상무·광천', region: 'honam', city: 'gwangju',
    title: '광주 상무·광천 출장마사지｜업무·터미널 생활권 안내', desc: '광주 상무지구 업무권과 광천 터미널 인접 생활권 이용 안내.',
    feature: '상무·광천은 상무지구 오피스·호텔권과 광천동 유스퀘어 터미널·복합상권이 이어지는 광주의 업무·교통 중심 생활권입니다. 상무지구 고층 오피스텔과 광천 상업지가 밀집해 유동 인구가 큽니다.',
    transport: '광주종합버스터미널(유스퀘어)과 도시철도 상무역·운천역이 축입니다.',
    stay: '상무지구 비즈니스 호텔과 오피스텔이 많아 업무 출장 체류가 많습니다.',
    programs: ['aroma-therapy', 'swedish'], nearby: ['gwangju-suwan-cheomdan', 'gwangju-downtown'] },
  { slug: 'gwangju-suwan-cheomdan', name: '광주 수완·첨단', region: 'honam', city: 'gwangju',
    title: '광주 수완·첨단 출장마사지｜신도시 주거 생활권 안내', desc: '광주 수완지구·첨단 신도시 아파트·상권 이용 기준 안내.',
    feature: '수완·첨단은 광산·북구의 신도시 생활권으로, 수완지구 상권·아파트와 첨단지구 연구·주거권이 이어집니다. 대단지 아파트와 신축 오피스텔이 많아 동·호수와 공동현관 출입 확인이 중요합니다.',
    transport: '첨단·수완을 잇는 간선도로와 광주송정역 접근성이 좋습니다.',
    stay: '신도시 오피스텔·레지던스가 있어 주거·업무 혼합 수요가 있습니다.',
    programs: ['aroma-therapy', 'foot-massage'], nearby: ['gwangju-sangmu-gwangcheon', 'gwangju-songjeong-station'] },
  { slug: 'gwangju-downtown', name: '광주 금남로·충장로', region: 'honam', city: 'gwangju',
    title: '광주 금남로·충장로 출장마사지｜원도심 상권 생활권 안내', desc: '광주 금남로·충장로 동구 원도심 상권 이용 기준 안내.',
    feature: '금남로·충장로는 광주 동구의 전통 원도심 상권 생활권입니다. 충장로 패션·먹자상권과 금남로 오피스, 국립아시아문화전당권이 이어지며, 구축과 신축 상가 건물이 함께 있습니다.',
    transport: '도시철도 금남로4가역·문화전당역이 지나며 도심 이동이 편리합니다.',
    stay: '원도심 비즈니스 숙소와 상권 숙소가 있어 도심 근거리 방문 수요가 이어집니다.',
    programs: ['foot-massage', 'aroma-therapy'], nearby: ['gwangju-sangmu-gwangcheon', 'gwangju-suwan-cheomdan'] },
  { slug: 'gwangju-songjeong-station', name: '광주송정역', region: 'honam', city: 'gwangju',
    title: '광주송정역 출장마사지｜KTX 역세권 생활권 안내', desc: '광주송정역 KTX 역세권과 송정 상권 숙소 이용 기준 안내.',
    feature: '광주송정역은 KTX 호남선의 관문으로, 광산구 송정 원도심 상권과 역세권 숙소가 이어집니다. 1913송정역시장 관광권과 역세권 비즈니스 숙소가 함께 있어 환승·출장 수요가 집중됩니다.',
    transport: 'KTX·SRT 광주송정역과 도시철도 송정공원역이 연결되어 접근성이 좋습니다.',
    stay: '역 인접 비즈니스 숙소가 많아 환승·단기 출장 숙박 수요가 큽니다.',
    programs: ['foot-massage', 'sports-massage'], nearby: ['gwangju-sangmu-gwangcheon', 'gwangju-suwan-cheomdan'] },

  // ── 강원 ──
  { slug: 'chuncheon-myeongdong-jungangro', name: '춘천 명동·중앙로', region: 'gangwon', city: 'chuncheon-si',
    title: '춘천 명동·중앙로 출장마사지｜원도심 상권 생활권 안내', desc: '춘천 명동·중앙로 원도심 상권과 역세권 숙소 이용 안내.',
    feature: '명동·중앙로는 춘천의 대표 원도심 상권 생활권으로, 춘천 명동 닭갈비골목과 중앙로 상권, 춘천역 인접권이 이어집니다. 도심 상가와 소규모 오피스가 밀집해 유동 인구가 큽니다.',
    transport: 'ITX 춘천역과 춘천시외버스터미널이 가까워 서울·시내 접근성이 좋습니다.',
    stay: '도심 비즈니스 숙소와 역 인접 숙소가 있어 단기 방문 수요가 이어집니다.',
    programs: ['sports-massage', 'thai-massage'], nearby: ['chuncheon-onui-toegye'] },
  { slug: 'chuncheon-onui-toegye', name: '춘천 온의·퇴계', region: 'gangwon', city: 'chuncheon-si',
    title: '춘천 온의·퇴계 출장마사지｜신주거·역세권 생활권 안내', desc: '춘천 온의·퇴계 신축 아파트와 남춘천역 생활권 이용 안내.',
    feature: '온의·퇴계는 남춘천역과 롯데·신축 주상복합이 들어선 춘천의 신주거 생활권입니다. 온의동 고층 아파트·오피스텔과 퇴계동 주거지가 이어지며 신축 건물 출입 방식 확인이 중요합니다.',
    transport: 'ITX 남춘천역과 시외버스터미널이 인접해 수도권 접근이 편리합니다.',
    stay: '남춘천역 인접 신축 오피스텔·숙소가 많아 업무·출장 수요가 늘고 있습니다.',
    programs: ['thai-massage', 'sports-massage'], nearby: ['chuncheon-myeongdong-jungangro'] },
  { slug: 'wonju-musil-dangye', name: '원주 무실·단계', region: 'gangwon', city: 'wonju-si',
    title: '원주 무실·단계 출장마사지｜도심 업무·주거 생활권 안내', desc: '원주 무실·단계 신도심 오피스·아파트 생활권 이용 안내.',
    feature: '무실·단계는 원주의 신도심 업무·주거 생활권으로, 무실동 오피스·상권과 단계동 아파트 단지가 밀집해 있습니다. 원주에서 인구가 가장 많은 생활권으로 오피스텔과 대단지 아파트 출입 확인이 중요합니다.',
    transport: '원주고속버스터미널과 시내 간선도로가 축이며, KTX 원주역(만종) 접근이 이어집니다.',
    stay: '무실동 비즈니스 호텔·오피스텔이 많아 업무 출장 체류가 많습니다.',
    programs: ['sports-massage', 'thai-massage'], nearby: ['wonju-bangok-innovation'] },
  { slug: 'wonju-bangok-innovation', name: '원주 반곡·혁신도시', region: 'gangwon', city: 'wonju-si',
    title: '원주 반곡·혁신도시 출장마사지｜공공기관 이전 생활권 안내', desc: '원주 반곡 혁신도시 신축 오피스텔·아파트 이용 기준 안내.',
    feature: '반곡·혁신도시는 국민건강보험공단 등 공공기관이 이전한 원주 혁신도시 생활권으로, 반곡동 신축 오피스텔과 아파트가 밀집해 있습니다. 도심에서 남동쪽으로 떨어져 있어 이동 동선 확인이 필요합니다.',
    transport: 'KTX 원주역(만종)과 혁신도시 간선도로가 축이며, 도심 무실동 이동이 이어집니다.',
    stay: '혁신도시 신축 오피스텔·숙소가 많아 공공기관 출장 체류 수요가 큽니다.',
    programs: ['sports-massage', 'aroma-therapy'], nearby: ['wonju-musil-dangye'] },
  { slug: 'gangneung-gyodong-yucheon', name: '강릉 교동·유천', region: 'gangwon', city: 'gangneung-si',
    title: '강릉 교동·유천 출장마사지｜도심·신주거 생활권 안내', desc: '강릉 교동·유천 도심 상권과 신축 주거 생활권 이용 안내.',
    feature: '교동·유천은 강릉의 도심·신주거 생활권으로, 교동 택지의 상권·아파트와 유천지구 신축 주거지가 이어집니다. 강릉 원도심과 인접해 도심 상가와 신축 아파트가 함께 있습니다.',
    transport: 'KTX 강릉역과 시내 간선도로가 가까워 도심·해안 이동이 편리합니다.',
    stay: '도심 비즈니스 숙소와 역 인접 숙소가 있어 관광·업무 수요가 함께 있습니다.',
    programs: ['aroma-therapy', 'foot-massage'], nearby: ['gangneung-gyeongpo-anmok'] },
  { slug: 'gangneung-gyeongpo-anmok', name: '강릉 경포·안목', region: 'gangwon', city: 'gangneung-si',
    title: '강릉 경포·안목 출장마사지｜해안 관광 숙소 생활권 안내', desc: '강릉 경포해변·안목 커피거리 해안 관광 숙소 이용 안내.',
    feature: '경포·안목은 경포호·경포해변과 안목 커피거리를 낀 강릉의 대표 해안 관광 생활권입니다. 해변을 따라 리조트·호텔·펜션이 밀집해 있어 성수기 숙소 이용 기준과 이동 동선이 중요합니다.',
    transport: 'KTX 강릉역에서 경포·안목까지 차량 이동이 이어지며, 해안 도로가 축입니다.',
    stay: '경포·안목 해안 리조트·호텔·펜션이 많아 계절 관광 숙박 수요가 뚜렷합니다.',
    programs: ['aroma-therapy', 'lomi-lomi'], nearby: ['gangneung-gyodong-yucheon'] },
  { slug: 'sokcho-joyang-gyodong', name: '속초 조양·교동', region: 'gangwon', city: 'sokcho-si',
    title: '속초 조양·교동 출장마사지｜도심·해변 생활권 안내', desc: '속초 조양·교동 도심 상권과 속초해변 인접 숙소 이용 안내.',
    feature: '조양·교동은 속초의 도심·해변 생활권으로, 조양동 아파트·상권과 교동 주거지, 속초해변·엑스포권이 이어집니다. 도심 주거와 해안 관광 숙소가 함께 있어 성수기 수요가 큽니다.',
    transport: '속초고속·시외버스터미널과 서울양양고속도로가 축이며, 철도가 없어 차량 이동 기준이 중요합니다.',
    stay: '속초해변 인접 리조트·호텔과 도심 숙소가 많아 관광 성수기 숙박 수요가 높습니다.',
    programs: ['aroma-therapy', 'couple'], nearby: ['yangyang-naksan-ingu'] },
  { slug: 'yangyang-naksan-ingu', name: '양양 낙산·인구', region: 'gangwon', city: 'yangyang-gun',
    title: '양양 낙산·인구 출장마사지｜서핑 해변 숙소 생활권 안내', desc: '양양 낙산해변·인구 서피비치 서핑 관광 숙소 이용 안내.',
    feature: '낙산·인구는 양양의 대표 해변 관광 생활권으로, 낙산해변·낙산사권과 인구·죽도·서피비치 서핑 성지가 이어집니다. 해변을 따라 펜션·게스트하우스·서핑 숙소가 흩어져 있어 위치 확인이 중요합니다.',
    transport: '서울양양고속도로와 양양시외버스터미널, 양양국제공항이 축이며, 해변권은 이동 동선을 확인합니다.',
    stay: '낙산·인구 해변 펜션·리조트와 서핑 숙소가 많아 성수기 해양 관광 수요가 높습니다.',
    programs: ['aroma-therapy', 'couple'], nearby: ['sokcho-joyang-gyodong'] },
  { slug: 'pyeongchang-daegwallyeong-yongpyong', name: '평창 대관령·용평', region: 'gangwon', city: 'pyeongchang-gun',
    title: '평창 대관령·용평 출장마사지｜스키·리조트 숙소 안내', desc: '평창 대관령 용평·알펜시아 스키·리조트 객실 이용 기준 안내.',
    feature: '대관령·용평은 평창의 스키·리조트 관광 생활권으로, 용평리조트·알펜시아·휘닉스파크 인접권이 이어집니다. 겨울 스키 성수기 수요가 크고 리조트 콘도·호텔 객실 출입 정책 확인이 핵심입니다.',
    transport: 'KTX 진부(오대산)역과 영동고속도로가 축이며, 리조트권은 겨울철 도로 상황을 확인합니다.',
    stay: '용평·알펜시아·휘닉스 리조트 콘도·호텔이 많아 리조트 객실 이용 기준을 우선 확인합니다.',
    programs: ['aroma-therapy', 'couple'], nearby: ['jeongseon-high1-resort'] },
  { slug: 'jeongseon-high1-resort', name: '정선 하이원리조트', region: 'gangwon', city: 'jeongseon-gun',
    title: '정선 하이원리조트 출장마사지｜사북·고한 리조트 숙소 안내', desc: '정선 하이원리조트·사북·고한 리조트 객실 이용 기준 안내.',
    feature: '하이원리조트권은 정선 사북·고한읍의 대표 산악 리조트 생활권으로, 하이원리조트 콘도·호텔과 강원랜드 인접권이 이어집니다. 산악 지형 리조트라 겨울철 이동 기준과 객실 출입 정책 확인이 중요합니다.',
    transport: '민둥산역(정선선)과 고한사북버스터미널, 영동고속도로 진입로가 축이며, 산간 도로 상황을 확인합니다.',
    stay: '하이원리조트 콘도·호텔과 고한·사북 숙소가 많아 리조트 객실 이용 기준을 우선 확인합니다.',
    programs: ['aroma-therapy', 'lomi-lomi'], nearby: ['pyeongchang-daegwallyeong-yongpyong'] },
];

module.exports = { lifeAreas };
